version: '3'
services:
  fastapi:
    container_name: fastapi_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: fastapi-image
    command: /start
    depends_on:
      - redis-cache
      - redis-celery
    volumes:
      - .:/app
      - /app/logs

  redis-celery:
    image: redis:7-alpine
    container_name: redis-celery
    ports:
      - "6379:6379"

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis-celery

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis-celery

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis-celery